# Generated by Django 3.0.1 on 2020-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target',
            field=models.IntegerField(),
        ),
    ]
